#!/bin/sh
#
# @name Esky (Big) Lama v4
#
# @type Coaxial Helicopter
# @class Copter
#
# @output MAIN1 Left swashplate servomotor, pitch axis
# @output MAIN2 Right swashplate servomotor, roll axis
# @output MAIN3 Upper rotor (CCW)
# @output MAIN4 Lower rotor (CW)
#
# @maintainer Emmanuel Roussel

# Altered to be my rotor module

echo "Rotor Module 81900_rotor_module config file runned!"

sh /etc/init.d/rc.rm_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.17
	param set MC_ROLLRATE_I 0.05
	param set MC_ROLLRATE_D 0.005
	param set MC_ROLLRATE_FF 0
	param set MC_PITCH_P 6.5
	param set MC_PITCHRATE_P 0.17
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCHRATE_D 0.005
	param set MC_PITCHRATE_FF 0
	param set MC_YAW_P 2
	param set MC_YAWRATE_P 0.1
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0
	param set MC_YAWRATE_FF 0

	param set NAV_ACC_RAD 2

fi

set MIXER_FILE etc/mixers-sitl/rotor_module.main.mix
set MIXER custom
